name: Netlify thing
on:
  workflow_dispatch:

jobs:
  run-jinxp:
    runs-on: ubuntu-latest
    name: Jinxp download & run
    timeout-minutes: 5
    steps:
      - name: Checkout EO-Scripts
        uses: actions/checkout@v4
      - name: Copy gameobj-data.xml and scripts for EO-Lich5
        run: |
          git clone https://github.com/elanthia-online/scripts.git
          curl -s https://api.github.com/repos/elanthia-online/jinxp/releases/latest \
          | grep browser_download_url \
          | grep jinxp \
          | cut -d '"' -f 4 \
          | wget -qi - \
          && chmod +x jinxp \
          && ./jinxp -i scripts/scripts
          cp -r /home/runner/work/testjinx/testjinx/dist/*     /home/runner/work/testjinx/testjinx/docs/
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"
          git add docs
          git commit -m "Automatic publish"
          git push
